/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      borderRadius: {
        'small': '8px',
        'control': '12px',
        'container': '16px',
        'large': '20px',
        'sidebar-item': '14px',
      },
      colors: {
        brand: {
          50:  '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
          800: '#5b21b6',
          900: '#4c1d95',
          950: '#2e1065',
        },
        bg: 'rgb(var(--bg) / <alpha-value>)',
        surface: 'rgb(var(--surface) / <alpha-value>)',
        'surface-2': 'rgb(var(--surface-2) / <alpha-value>)',
        'surface-3': 'rgb(var(--surface-3) / <alpha-value>)',
        border: 'rgb(var(--border) / <alpha-value>)',
        'border-strong': 'rgb(var(--border-strong) / <alpha-value>)',
        'text-primary': 'rgb(var(--text-primary) / <alpha-value>)',
        'text-secondary': 'rgb(var(--text-secondary) / <alpha-value>)',
        'text-tertiary': 'rgb(var(--text-tertiary) / <alpha-value>)',
        'text-muted': 'rgb(var(--text-muted) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        display: ['"Inter Display"', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        'soft': '0 1px 2px rgba(15, 23, 42, 0.04), 0 1px 3px rgba(15, 23, 42, 0.04)',
        'card': '0 1px 2px rgba(15, 23, 42, 0.04), 0 4px 16px -2px rgba(15, 23, 42, 0.06)',
        'card-hover': '0 6px 24px -4px rgba(15, 23, 42, 0.12), 0 12px 40px -8px rgba(15, 23, 42, 0.08)',
        'glow': '0 0 0 1px rgba(139, 92, 246, 0.15), 0 8px 32px -4px rgba(139, 92, 246, 0.35)',
        'glow-sm': '0 4px 16px -2px rgba(139, 92, 246, 0.25)',
      },
      backgroundImage: {
        'gradient-brand': 'linear-gradient(135deg, #8b5cf6 0%, #6366f1 100%)',
        'gradient-radial': 'radial-gradient(ellipse at center, var(--tw-gradient-stops))',
      },
      keyframes: {
        'fade-in': {'0%': {opacity: '0'}, '100%': {opacity: '1'}},
        'fade-up': {'0%': {opacity: '0', transform: 'translateY(12px)'}, '100%': {opacity: '1', transform: 'translateY(0)'}},
        'fade-down': {'0%': {opacity: '0', transform: 'translateY(-8px)'}, '100%': {opacity: '1', transform: 'translateY(0)'}},
        'scale-in': {'0%': {opacity: '0', transform: 'scale(0.96)'}, '100%': {opacity: '1', transform: 'scale(1)'}},
        'slide-in-right': {'0%': {opacity: '0', transform: 'translateX(12px)'}, '100%': {opacity: '1', transform: 'translateX(0)'}},
        'shimmer': {'0%': {backgroundPosition: '-200% 0'}, '100%': {backgroundPosition: '200% 0'}},
        'gradient-x': {'0%, 100%': {backgroundPosition: '0% 50%'}, '50%': {backgroundPosition: '100% 50%'}},
        'blob': {'0%, 100%': {transform: 'translate(0,0) scale(1)'}, '33%': {transform: 'translate(30px,-50px) scale(1.1)'}, '66%': {transform: 'translate(-20px,20px) scale(0.9)'}},
        'spin-slow': {'0%': {transform: 'rotate(0deg)'}, '100%': {transform: 'rotate(360deg)'}},
        'pulse-soft': {'0%, 100%': {opacity: '1'}, '50%': {opacity: '0.6'}},
        'count-up': {'0%': {opacity: '0', transform: 'translateY(8px)'}, '100%': {opacity: '1', transform: 'translateY(0)'}},
      },
      animation: {
        'fade-in': 'fade-in 0.4s ease-out both',
        'fade-up': 'fade-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
        'fade-down': 'fade-down 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'scale-in': 'scale-in 0.3s cubic-bezier(0.16, 1, 0.3, 1) both',
        'slide-in-right': 'slide-in-right 0.4s cubic-bezier(0.16, 1, 0.3, 1) both',
        'shimmer': 'shimmer 1.8s linear infinite',
        'gradient-x': 'gradient-x 8s ease infinite',
        'blob': 'blob 14s ease-in-out infinite',
        'spin-slow': 'spin-slow 8s linear infinite',
        'pulse-soft': 'pulse-soft 2.4s ease-in-out infinite',
        'count-up': 'count-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) both',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
    },
  },
  plugins: [],
}
